site_name: SCLab Documentation
site_description: Documentation for SCLab - Single-Cell Analysis Tools
repo_url: https://github.com/umbibio/sclab

theme:
  name: material
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep-purple
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep-purple
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  # - Tutorials:
  #     - Quick Start: tutorials/quickstart.ipynb

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - mkdocs-jupyter:
      include_source: true
      ignore_h1_titles: true
