name: Upload Python Package

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"  # Matches version tags like v0.1.3

jobs:
  test:
    name: Run Tests
    uses: ./.github/workflows/tests.yml

  publish-release:
    needs: test  # Require tests to pass first
    name: Publish GitHub Release
    uses: ./.github/workflows/release.yml
    permissions:
      contents: write  # Needed for tag operations and creating releases

  deploy:
    needs: publish-release
    name: Deploy to PyPI
    runs-on: ubuntu-latest
    environment: pypi-release
    permissions:
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build package
      run: python -m build

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
